version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kinghamm-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/kinghamm?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: kinghamm-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=kinghamm
    volumes:
      - /home/kinghamm/clothes/db:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local